# Generated by Django 5.1.8 on 2025-05-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=50)),
                ('name_official', models.CharField(max_length=100)),
                ('tld', models.JSONField(blank=True, null=True)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('ccn3', models.CharField(blank=True, max_length=3, null=True)),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('cioc', models.CharField(blank=True, max_length=3, null=True)),
                ('independent', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('un_member', models.BooleanField(default=False)),
                ('currencies', models.JSONField(blank=True, null=True)),
                ('idd_root', models.CharField(blank=True, max_length=10, null=True)),
                ('idd_suffixes', models.JSONField(blank=True, null=True)),
                ('capital', models.JSONField(blank=True, null=True)),
                ('alt_spellings', models.JSONField(blank=True, null=True)),
                ('subregion', models.CharField(blank=True, max_length=50, null=True)),
                ('translations', models.JSONField(blank=True, null=True)),
                ('latlng', models.JSONField(blank=True, null=True)),
                ('landlocked', models.BooleanField(default=False)),
                ('borders', models.JSONField(blank=True, null=True)),
                ('area', models.FloatField()),
                ('demonyms', models.JSONField(blank=True, null=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('maps_google', models.URLField(blank=True, null=True)),
                ('maps_openstreet', models.URLField(blank=True, null=True)),
                ('population', models.BigIntegerField()),
                ('gini', models.JSONField(blank=True, null=True)),
                ('fifa', models.CharField(blank=True, max_length=3, null=True)),
                ('car_signs', models.JSONField(blank=True, null=True)),
                ('car_side', models.CharField(blank=True, max_length=10, null=True)),
                ('timezones', models.JSONField(blank=True, null=True)),
                ('continents', models.JSONField(blank=True, null=True)),
                ('flag_png', models.URLField(blank=True, null=True)),
                ('flag_svg', models.URLField(blank=True, null=True)),
                ('flag_alt', models.TextField(blank=True, null=True)),
                ('coat_of_arms_png', models.URLField(blank=True, null=True)),
                ('coat_of_arms_svg', models.URLField(blank=True, null=True)),
                ('start_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('capital_info_latlng', models.JSONField(blank=True, null=True)),
                ('postal_code_format', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code_regex', models.TextField(blank=True, null=True)),
                ('native_names', models.JSONField(blank=True, null=True)),
                ('languages', models.ManyToManyField(to='country_finder.language')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='country_finder.region')),
            ],
        ),
    ]
